# Generated by Django 4.2.5 on 2023-12-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('endpoint', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_is_model', models.BooleanField(null=True)),
                ('user_guess', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ai')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('model_answer', models.CharField(blank=True, max_length=300, null=True)),
                ('human_answer', models.CharField(blank=True, max_length=300, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.game')),
            ],
        ),
    ]
