# Generated by Django 4.2.5 on 2023-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(blank=True, max_length=300, null=True)),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
